package com.vadym.gvd.bestfriendskotlin.easter_egg

import com.vadym.gvd.bestfriendskotlin.R

object CoinSeeds {
    val ALL_COINS = listOf(
        CoinEntity("coin_info_001", "InfoView", R.id.coin_info_001),
        CoinEntity("coin_info_002", "InfoView", R.id.coin_info_002),
        CoinEntity("coin_info_003", "InfoView", R.id.coin_info_003),
        CoinEntity("coin_exercise_4", "ExerciseView", R.id.coin_exercise_4),
        CoinEntity("coin_exercise_5", "ExerciseView", R.id.coin_exercise_5),
        CoinEntity("coin_exercise_6", "ExerciseView", R.id.coin_exercise_6),
        CoinEntity("coin_exercise_7", "ExerciseView", R.id.coin_exercise_7),
        CoinEntity("coin_hcalendar_8", "HeavenlyCalendarView", R.id.coin_hcalendar_8),
        CoinEntity("coin_hcalendar_9", "HeavenlyCalendarView", R.id.coin_hcalendar_9),
        CoinEntity("coin_hdh_10", "HDHView", R.id.coin_hdh_10),
        CoinEntity("coin_hdh_11", "HDHView", R.id.coin_hdh_11),
        CoinEntity("coin_phrase_12", "PhraseForDay", R.id.coin_phrase_12),
        CoinEntity("coin_phrase_13", "PhraseForDay", R.id.coin_phrase_13),
        CoinEntity("coin_anthem_14", "AnthemView", R.id.coin_anthem_14),
        CoinEntity("coin_anthem_15", "AnthemView", R.id.coin_anthem_15),
        CoinEntity("coin_anthem_16", "AnthemView", R.id.coin_anthem_16),
        CoinEntity("coin_kido_17", "PersonView", R.id.coin_kido_17),
        CoinEntity("coin_kido_18", "PersonView", R.id.coin_kido_18),
        CoinEntity("coin_kido_19", "PersonView", R.id.coin_kido_19),
        CoinEntity("coin_kido_20", "PersonView", R.id.coin_kido_20),
        CoinEntity("coin_kido_21", "PersonView", R.id.coin_kido_21),
        CoinEntity("coin_condition_22", "ConditionView", R.id.coin_condition_22),
        CoinEntity("coin_condition_23", "ConditionView", R.id.coin_condition_23),
        CoinEntity("coin_condition_24", "ConditionView", R.id.coin_condition_24),
        CoinEntity("coin_condition_25", "ConditionView", R.id.coin_condition_25),
        CoinEntity("coin_condition_26", "ConditionView", R.id.coin_condition_26),
        CoinEntity("coin_condition_27", "ConditionView", R.id.coin_condition_27),
        CoinEntity("coin_father_28", "FatherKidoView", R.id.coin_father_28),
        CoinEntity("coin_father_29", "FatherKidoView", R.id.coin_father_29),
        CoinEntity("coin_father_nadezdy_30", "FatherKidoNadezdyViewIntro", R.id.coin_father),
        CoinEntity("coin_father_nadezdy_31", "FatherKidoNadezdyViewIntro", R.id.coin_father2),
        CoinEntity("coin_father_nadezdy_32", "FatherKidoNadezdyViewIntro", R.id.coin_father3),
        CoinEntity("coin_father_pobedy_33", "FatherKidoPobedyViewIntro", R.id.coin_father),
        CoinEntity("coin_father_pobedy_34", "FatherKidoPobedyViewIntro", R.id.coin_father2),
        CoinEntity("coin_father_pobedy_35", "FatherKidoPobedyViewIntro", R.id.coin_father3),
        CoinEntity("coin_father_serdca_36", "FatherKidoSerdcaViewIntro", R.id.coin_father),
        CoinEntity("coin_father_serdca_37", "FatherKidoSerdcaViewIntro", R.id.coin_father2),
        CoinEntity("coin_father_serdca_38", "FatherKidoSerdcaViewIntro", R.id.coin_father3),
        CoinEntity("coin_father_zelaniya_39", "FatherKidoZelaniyaViewIntro", R.id.coin_father),
        CoinEntity("coin_father_zelaniya_40", "FatherKidoZelaniyaViewIntro", R.id.coin_father2),
        CoinEntity("coin_father_zelaniya_41", "FatherKidoZelaniyaViewIntro", R.id.coin_father3),
        CoinEntity("coin_father_unification_42", "FatherKidoUnificationViewIntro", R.id.coin_father),
        CoinEntity("coin_father_unification_43", "FatherKidoUnificationViewIntro", R.id.coin_father2),
        CoinEntity("coin_father_unification_44", "FatherKidoUnificationViewIntro", R.id.coin_father3),
        CoinEntity("coin_father_reshimosty_45", "FatherKidoReshimostyViewIntro", R.id.coin_father),
        CoinEntity("coin_father_reshimosty_46", "FatherKidoReshimostyViewIntro", R.id.coin_father2),
        CoinEntity("coin_father_reshimosty_47", "FatherKidoReshimostyViewIntro", R.id.coin_father3),
        CoinEntity("coin_father_pochtitelnosty_48", "FatherKidoPochtitelnostyViewIntro", R.id.coin_father),
        CoinEntity("coin_father_pochtitelnosty_49", "FatherKidoPochtitelnostyViewIntro", R.id.coin_father2),
        CoinEntity("coin_father_pochtitelnosty_50", "FatherKidoPochtitelnostyViewIntro", R.id.coin_father3),

        CoinEntity("coin_tradition1", "GeneralViewContent", R.id.coin_tradition1),
        CoinEntity("coin_tradition2", "GeneralViewContent", R.id.coin_tradition2),
        CoinEntity("coin_tradition3", "GeneralViewContent", R.id.coin_tradition3),
        CoinEntity("coin_tradition4", "GeneralViewContent", R.id.coin_tradition4),

//        CoinEntity("coin_tradition1", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition2", "GeneralViewContent", R.id.coin_tradition2),
//        CoinEntity("coin_tradition3", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_PLEDGE", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition2_PLEDGE", "GeneralViewContent", R.id.coin_tradition2),
//        CoinEntity("coin_tradition3_PLEDGE", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_PLEDGE", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_ANSHIIL", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition2_ANSHIIL", "GeneralViewContent", R.id.coin_tradition2),
//        CoinEntity("coin_tradition3_ANSHIIL", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_ANSHIIL", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition3_PHOTO", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_PHOTO", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_DAY8", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition3_DAY8", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_DAY8", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_BIRTHDAY", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition3_BIRTHDAY", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_BIRTHDAY", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_CLOTHES", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition3_CLOTHES", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_CLOTHES", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_LS", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition2_LS", "GeneralViewContent", R.id.coin_tradition2),
//        CoinEntity("coin_tradition3_LS", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_LS", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_SONGHWA", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition2_SONGHWA", "GeneralViewContent", R.id.coin_tradition2),
//        CoinEntity("coin_tradition3_SONGHWA", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_SONGHWA", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition2_PRAYER", "GeneralViewContent", R.id.coin_tradition2),
//        CoinEntity("coin_tradition3_PRAYER", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_PRAYER", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition3_DESYATYNA", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_DESYATYNA", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_SALT", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition2_SALT", "GeneralViewContent", R.id.coin_tradition2),
//        CoinEntity("coin_tradition3_SALT", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_SALT", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_VINE", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition3_VINE", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_VINE", "GeneralViewContent", R.id.coin_tradition4),
//
//        CoinEntity("coin_tradition1_CANDLE", "GeneralViewContent", R.id.coin_tradition1),
//        CoinEntity("coin_tradition3_CANDLE", "GeneralViewContent", R.id.coin_tradition3),
//        CoinEntity("coin_tradition4_CANDLE", "GeneralViewContent", R.id.coin_tradition4),
    )
}